server.port=8080

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# para cargar los datos del archivo sql de pruebas
# spring.sql.init.mode=always

langchain4j.open-ai.chat-model.log-responses=true
langchain4j.open-ai.chat-model.log-requests=true
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG