spring.datasource.url=${SPRING_DATASOURCE_URL_PROD}

# Cargar datos iniciales (data.sql) en MySQL al arrancar
#spring.sql.init.mode=always
springdoc.api-docs.enabled=false

# Docker Compose integration (disabled in prod)
spring.docker.compose.enabled=false
springdoc.swagger-ui.enabled=false
