server.port=8080

# Docker Compose integration (dev only)
spring.docker.compose.enabled=true
spring.docker.compose.file=./docker-compose.yml
spring.docker.compose.lifecycle-management=start_and_stop
spring.docker.compose.skip.in-tests=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Cargar datos iniciales (data.sql) en MySQL al arrancar
#spring.sql.init.mode=always
# Asegura que Hibernate cree/actualice las tablas antes de ejecutar data.sql
#spring.jpa.defer-datasource-initialization=true

langchain4j.open-ai.chat-model.log-responses=true
langchain4j.open-ai.chat-model.log-requests=true
logging.level.dev.langchain4j=DEBUG
logging.level.dev.ai4j.openai4j=DEBUG