package com.backend.usersapp.backend_usersapp.web.controllers;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.backend.usersapp.backend_usersapp.domain.services.GreetingAiService;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;

@RestController
@RequestMapping("/hello")
@CrossOrigin(origins = "http://localhost:5173")
//@CrossOrigin(originPatterns = "*", allowCredentials = "true")
@Tag(name = "Hello", description = "hello-controller: Greeting endpoint")
public class HelloController {

    private final String plataform;
    private final GreetingAiService aiService;

    public HelloController(@Value("${spring.application.name}") String plataform, GreetingAiService aiService) {
        System.out.println(plataform);
        this.plataform = plataform;
        this.aiService = aiService;
    }

    @GetMapping(produces = "text/plain")
    @Operation(
            summary = "Generate greeting message",
            description = "Returns a greeting generated by the AI service using the application name.",
            responses = {
                @ApiResponse(responseCode = "200", description = "Greeting generated",
                        content = @Content(mediaType = "text/plain", schema = @Schema(implementation = String.class)))
            }
    )
    public String hello() {
        return this.aiService.generateGreeting(plataform);
    }

}
